# 6.0 required for FBSnapshotTestCase
platform :ios, '6.0'
use_frameworks!

target "NUIDemo" do
  pod "NUIParse"
end

target "NUITests" do
  pod 'FBSnapshotTestCase', '~> 1.6'
  pod 'UIImage+ColorFromImage', '0.0.2'
end
